include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Static Routing
LUCI_DEPENDS:=+luci-mod-network
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
