#!/bin/sh

if [ -e "/etc/config/lora" ]; then
	REGION=$(uci get lora.radio.region)
	FREQ_PLAN=$(uci get lora.radio.channel_plan)
	DEVICE=$(uci get lora.radio.device)
	FREQ=$(uci get lora.radio.freq_plan)
	
	if [ -n "$REGION" -a -n "$FREQ_PLAN" -a -n "$DEVICE" -a -n "$FREQ" ];then
		exit 0
	fi
else 
	touch /etc/config/lora_radio
fi

if [ -e "/etc/deviceinfo/freq_plan" ]; then
	region=$(cat /etc/deviceinfo/freq_plan)
	case "$region" in
		"915" | "US915") REGION_MODEM="US915"; FREQ_PLAN="US_902_928_FSB_1"; DEVICE="US915"; FREQ="us915_1";;
		"868" | "EU868") REGION_MODEM="EU868"; FREQ_PLAN="EU_863_870_TTN"; DEVICE="EU868"; FREQ="eu868";;
		*) REGION_MODEM="US915";  FREQ_PLAN="US_902_928_FSB_1"; DEVICE="US915";;
	esac
else
	REGION_MODEM="US915";  FREQ_PLAN="US_902_928_FSB_1"; DEVICE="US915"; FREQ="us915_1";
fi

uci set lora.radio.region="$REGION_MODEM"
uci set lora.radio.channel_plan="$FREQ_PLAN"
uci set lora.radio.device="$DEVICE"
uci set lora.radio.freq_plan="$FREQ"

uci set packetforwarder.sx130x.region="$REGION_MODEM"
uci set basicstation.sx130x.region="$REGION_MODEM"
uci set packetforwarder.sx130x.channel_plan="$FREQ_PLAN"

uci commit lora.radio
uci commit packetforwarder.sx130x
uci commit basicstation.sx130x

exit 0